# Based on this source:
# https://waylonwalker.com/install-rust/
---
- name: Provision a debian VM for STM32f103 development using rust
  hosts: all
  vars:
    rustup_script_tag: "1.28.2"
    rustup_script_url: "https://raw.githubusercontent.com/rust-lang/rustup/refs/tags/{{ rustup_script_tag }}/rustup-init.sh"
    rustup_script_sha: "17247e4bcacf6027ec2e11c79a72c494c9af69ac8d1abcc1b271fa4375a106c2"

  pre_tasks:
    - name: Update apt repositories
      become_user: root
      become: true
      ansible.builtin.apt:
        update_cache: true

  tasks:
    - name: Check if cargo is installed
      ansible.builtin.shell:
        cmd: command -v cargo &> /dev/null
      register: cargo_exists
      ignore_errors: true
      failed_when: cargo_exists.rc != 0

    - name: Download rustup-init.sh installer if cargo is missing
      when: cargo_exists is failed
      ansible.builtin.get_url:
        url: "{{ rustup_script_url }}"
        dest: /tmp/rustup-init.sh
        mode: '0755'
        force: true
        checksum: "sha256:{{ rustup_script_sha }}"

    - name: Run rustup-init.sh installer if downloaded
      when: cargo_exists is failed
      ansible.builtin.command: /tmp/rustup-init.sh -y

    - name: Install build dependencies
      become_user: root
      become: true
      ansible.builtin.apt:
        name: build-essential
        state: present
        install_recommends: true
