# Based on this source:
# https://waylonwalker.com/install-rust/
---
- name: Setup a debian VM development environment for the STM32f103
  hosts: all
  become_user: "{{ ansible_user }}"
  become: true
  vars:
    rustup_script_tag: "1.28.2"
    rustup_script_str: "rustup-init.sh"
    rustup_script_url: "https://raw.githubusercontent.com/rust-lang/rustup/refs/tags/{{ rustup_script_tag }}/{{ rustup_script_str }}"
    rustup_script_sha: "17247e4bcacf6027ec2e11c79a72c494c9af69ac8d1abcc1b271fa4375a106c2"
    rustup_script_dst: "/home/{{ ansible_user }}/{{ rustup_script_str }}"
    toolchain_target: "thumbv7m-none-eabi"
    cargo_env: "/home/{{ ansible_user }}/.cargo/env"

  pre_tasks:
    - name: Update apt repositories
      become_user: root
      become: true
      ansible.builtin.apt:
        update_cache: true

  tasks:

    - name: Check if cargo env is setup
      ansible.builtin.stat:
        path: "{{ cargo_env }}"
      register: is_cargo_env

    - name: "Download installer: {{ rustup_script_str }}"
      ansible.builtin.get_url:
        url: "{{ rustup_script_url }}"
        dest: "{{ rustup_script_dst }}"
        mode: '0755'
        force: true
        checksum: "sha256:{{ rustup_script_sha }}"

    - name: "Run installer: {{ rustup_script_str }}"
      ansible.builtin.command: "{{ rustup_script_dst }} -y"
      when: is_cargo_env.stat.islnk is not defined
      changed_when: is_cargo_env.stat.islnk is defined

    - name: Install core glibc build deps
      become_user: root
      become: true
      ansible.builtin.apt:
        name:
          - build-essential
        state: present
        install_recommends: true

    - name: Install HW debugging utils
      become_user: root
      become: true
      ansible.builtin.apt:
        name:
          - gdb-arm-none-eabi
          - openocd
          - qemu-system-arm
          - usbutils
          - acl
        state: present
        install_recommends: true

    - name: Install Cortex-M3 toolchain for cross-compiling
      ansible.builtin.shell: |-
        . {{ cargo_env }}
        rustup target add {{ toolchain_target }}

    - name: Install LLVM tools for inspecting binaries
      ansible.builtin.shell: |-
        . {{ cargo_env }}
        cargo install cargo-binutils
        rustup component add llvm-tools

    - name: Install cargo-generate deps
      become_user: root
      become: true
      ansible.builtin.apt:
        name:
          - libssl-dev
          - pkg-config
        state: present
        install_recommends: true

    - name: Install cargo-generate
      ansible.builtin.shell: |-
        . {{ cargo_env }}
        cargo install cargo-generate

    - name: Install probe-rs-tools deps
      become_user: root
      become: true
      ansible.builtin.apt:
        name:
          - pkg-config
          - libudev-dev
          - cmake
          - git
        state: present
        install_recommends: true

    - name: Install probe-rs, cargo-flash, and cargo-embed
      # https://probe.rs/docs/getting-started/installation/
      ansible.builtin.shell: |-
        . {{ cargo_env }}
        cargo install probe-rs-tools --locked
